export const SERVICE_CATALOG = [
  {
    name: "Cabinet Painting and Refinishing",
    slug: "cabinet-painting-refinishing",
    category: "interior" as const,
    useCases: ["Kitchen cabinet updates", "Built-in shelving", "Bathroom vanities"],
    materials: ["Bonding primer", "Cabinet-grade enamel", "Low-VOC cleaners"],
  },
  {
    name: "Epoxy Flooring",
    slug: "epoxy-flooring",
    category: "interior" as const,
    useCases: ["Garages", "Workshops", "Light commercial floors"],
    materials: ["Concrete degreaser", "Two-part epoxy", "Slip-resistant aggregate"],
  },
  {
    name: "Interior Painting",
    slug: "interior-painting",
    category: "interior" as const,
    useCases: ["Occupied homes", "Move-in refreshes", "Offices and retail rooms"],
    materials: ["Low-VOC wall paint", "Stain-blocking primer", "Durable trim enamel"],
  },
  {
    name: "Wallpaper Removal",
    slug: "wallpaper-removal",
    category: "interior" as const,
    useCases: ["Dated wallcoverings", "Damaged seams", "Paint-ready wall restoration"],
    materials: ["Low-moisture removal solution", "Skim-coat compound", "Problem-surface primer"],
  },
  {
    name: "Brick Painting and Staining",
    slug: "brick-painting-staining",
    category: "exterior" as const,
    useCases: ["Masonry color updates", "Fireplace surrounds", "Exterior brick facades"],
    materials: ["Masonry cleaner", "Breathable mineral stain", "Masonry coating"],
  },
  {
    name: "Concrete Staining",
    slug: "concrete-staining",
    category: "exterior" as const,
    useCases: ["Patios", "Walkways", "Covered concrete floors"],
    materials: ["Concrete cleaner", "Penetrating stain", "UV-stable sealer"],
  },
  {
    name: "Deck Painting and Staining",
    slug: "deck-painting-staining",
    category: "exterior" as const,
    useCases: ["Weathered decks", "Porches", "Exterior stairs and rails"],
    materials: ["Wood brightener", "Penetrating deck stain", "Exterior porch coating"],
  },
  {
    name: "Exterior Painting",
    slug: "exterior-painting",
    category: "exterior" as const,
    useCases: ["Whole-home repaints", "Trim and fascia", "Commercial exteriors"],
    materials: ["Exterior bonding primer", "Weather-resistant acrylic", "Elastomeric sealant"],
  },
  {
    name: "Fence Painting and Staining",
    slug: "fence-painting-staining",
    category: "exterior" as const,
    useCases: ["Privacy fences", "Decorative wood fencing", "Gates and posts"],
    materials: ["Wood cleaner", "Penetrating stain", "Exterior enamel"],
  },
  {
    name: "Home Siding Painting",
    slug: "home-siding-painting",
    category: "exterior" as const,
    useCases: ["Fiber-cement siding", "Wood siding", "Paintable metal siding"],
    materials: ["Siding-safe cleaner", "Adhesion primer", "Premium exterior acrylic"],
  },
  {
    name: "Stucco Painting",
    slug: "stucco-painting",
    category: "exterior" as const,
    useCases: ["Faded stucco", "Hairline crack repair", "Color modernization"],
    materials: ["Masonry conditioner", "Elastomeric patch", "Breathable acrylic coating"],
  },
] as const;
