import type { CSSProperties } from "react";
import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Phone } from "lucide-react";
import { headers } from "next/headers";
import { notFound } from "next/navigation";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

export const dynamic = "force-dynamic";
type RouteParams = { tenantId: string; path?: string[] };

async function loadLive(tenantId: string, path: string) {
  const supabase = createSupabaseAdminClient(); if (!supabase) return null; const requestHeaders = await headers(); const host = requestHeaders.get("x-tenant-host") ?? requestHeaders.get("host") ?? "";
  const { data: domain } = await supabase.from("domains").select("hostname").eq("tenant_id", tenantId).eq("hostname", host).eq("is_primary", true).eq("is_verified", true).eq("is_preview", false).eq("launch_status", "launched").maybeSingle(); if (!domain) return null;
  const { data: tenant } = await supabase.from("tenants").select("id,company_name,phone,email,service_area,production_ready,launch_status,onboarding_submission_id").eq("id", tenantId).eq("production_ready", true).eq("launch_status", "launched").maybeSingle(); if (!tenant) return null;
  const [{ data: branding }, { data: pages }] = await Promise.all([supabase.from("branding_settings").select("primary_color,secondary_color,accent_color,theme,logo_path").eq("tenant_id", tenantId).single(), supabase.from("pages").select("page_name,nav_label,slug,h1,intro_copy,body_content,cta_text,page_type,seo_title,meta_description").eq("tenant_id", tenantId).eq("status", "published").eq("is_indexable", true).order("page_type").order("page_name")]);
  const page = pages?.find((item) => item.slug === path); if (!page) return null; const [{ data: versions }, { data: mediaFiles }] = await Promise.all([supabase.from("generated_content_versions").select("draft_data,version").eq("tenant_id", tenantId).eq("entity_type", "page").eq("entity_key", page.slug || "home").eq("status", "approved").order("version", { ascending: false }).limit(1), tenant.onboarding_submission_id ? supabase.from("onboarding_files").select("field_key,processed_outputs,approved_alt_text").eq("submission_id", tenant.onboarding_submission_id).in("section_key", ["projects_gallery", "branding"]) : Promise.resolve({ data: [] })]); const heroFile = (mediaFiles ?? []).find((file) => file.field_key.includes("photos") && Array.isArray(file.processed_outputs)) ?? (mediaFiles ?? []).find((file) => file.field_key === "brand_collateral" && Array.isArray(file.processed_outputs)); const outputs = heroFile?.processed_outputs as Array<{ storagePath?: string }> | undefined; const heroPath = outputs?.at(-1)?.storagePath; const heroImage = heroPath ? { src: supabase.storage.from("tenant-media").getPublicUrl(heroPath).data.publicUrl, alt: heroFile?.approved_alt_text ?? "" } : undefined; return { host, domain, tenant, branding, pages: pages ?? [], page, draft: versions?.[0]?.draft_data as { title?: string; summary?: string; sections?: Array<{ heading?: string; body?: string }> } | undefined, heroImage };
}

export async function generateMetadata({ params }: { params: Promise<RouteParams> }): Promise<Metadata> {
  const { tenantId, path: parts = [] } = await params; const data = await loadLive(tenantId, parts.join("/")); if (!data) return { title: "Page not found", robots: { index: false, follow: false } }; const canonical = `https://${data.host}/${parts.join("/")}`.replace(/\/$/, parts.length ? "" : "/"); return { title: data.page.seo_title, description: data.page.meta_description, alternates: { canonical }, robots: { index: true, follow: true }, openGraph: { title: data.page.seo_title, description: data.page.meta_description, url: canonical, type: "website" } };
}

export default async function LiveTenantPage({ params }: { params: Promise<RouteParams> }) {
  const { tenantId, path: parts = [] } = await params; const data = await loadLive(tenantId, parts.join("/")); if (!data) notFound(); const style = { "--live-primary": data.branding?.primary_color ?? "#17463d", "--live-secondary": data.branding?.secondary_color ?? "#eef3f0", "--live-accent": data.branding?.accent_color ?? "#f2b84b" } as CSSProperties; const sections = data.draft?.sections?.filter((item) => item.heading && item.body) ?? [];
  return <div className="live-tenant" style={style}><header className="live-header"><Link href="/">{data.tenant.company_name}</Link><nav>{data.pages.filter((item) => item.page_type === "core").map((item) => <Link key={item.slug} href={item.slug ? `/${item.slug}` : "/"}>{item.nav_label}</Link>)}</nav><a href={`tel:${data.tenant.phone.replace(/\D/g, "")}`}><Phone size={18}/><span>{data.tenant.phone}</span></a></header><main><section className="live-hero">{data.heroImage && <Image src={data.heroImage.src} alt={data.heroImage.alt} fill unoptimized sizes="100vw"/>}<div><p className="eyebrow">Serving {data.tenant.service_area}</p><h1>{data.draft?.title || data.page.h1}</h1><p>{data.draft?.summary || data.page.intro_copy}</p><Link className="button" href="/contact">{data.page.cta_text}<ArrowRight size={18}/></Link></div></section><section className="live-content">{sections.map((section) => <article key={section.heading}><h2>{section.heading}</h2><p>{section.body}</p></article>)}</section>{parts.length === 0 && <section className="live-links"><p className="eyebrow">Services and resources</p><h2>Explore the work</h2><div>{data.pages.filter((item) => item.slug).map((item) => <Link key={item.slug} href={`/${item.slug}`}><strong>{item.page_name}</strong><span>{item.page_type}</span><ArrowRight size={16}/></Link>)}</div></section>}</main><footer className="live-footer"><strong>{data.tenant.company_name}</strong><span>{data.tenant.phone} · {data.tenant.email}</span><span>{data.tenant.service_area}</span></footer></div>;
}
