import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getAiProvider } from "@/lib/ai/provider";
import { buildSourceFacts } from "@/lib/generation/source-profile";
import { onboardingWriteRequestIsAllowed } from "@/lib/onboarding/request-security";
import { requirePlatformAdmin } from "@/lib/security/dashboard-auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

const schema = z.object({ action: z.enum(["save", "approve", "request_changes", "regenerate"]), draftData: z.record(z.string(), z.unknown()).optional() });
export const maxDuration = 120;
export async function PATCH(request: NextRequest, { params }: { params: Promise<{ id: string; contentId: string }> }) {
  const access = await requirePlatformAdmin(); if (access.readOnly) return NextResponse.json({ message: "Content review is disabled in demo mode." }, { status: 503 }); const security = onboardingWriteRequestIsAllowed(request, 512_000); if (!security.allowed) return NextResponse.json({ message: security.message }, { status: security.status }); const parsed = schema.safeParse(await request.json()); if (!parsed.success || (parsed.data.action === "save" && !parsed.data.draftData)) return NextResponse.json({ message: "Content action is invalid." }, { status: 422 });
  const { id, contentId } = await params; const supabase = createSupabaseAdminClient()!; const { data: version } = await supabase.from("generated_content_versions").select("id,job_id,tenant_id,entity_type,entity_key,version,provider,model,prompt_version,source_fact_ids,draft_data").eq("id", contentId).single(); if (!version) return NextResponse.json({ message: "Content version not found." }, { status: 404 }); const { data: job } = await supabase.from("website_generation_jobs").select("id,invitation_id,submission_id").eq("id", version.job_id).eq("invitation_id", id).single(); if (!job) return NextResponse.json({ message: "Content does not belong to this invitation." }, { status: 403 });
  if (parsed.data.action === "approve" || parsed.data.action === "request_changes") { const status = parsed.data.action === "approve" ? "approved" : "changes_requested"; await supabase.from("generated_content_versions").update({ status }).eq("id", contentId); await supabase.from("approval_records").insert({ invitation_id: id, submission_id: job.submission_id, job_id: job.id, tenant_id: version.tenant_id, scope: "page", subject_key: `${version.entity_type}:${version.entity_key}:v${version.version}`, status, actor_type: "platform_admin", actor_id: access.userId, snapshot: { content_version_id: contentId } }); return NextResponse.json({ message: parsed.data.action === "approve" ? "Version approved as a draft. It was not published." : "Version marked for changes." }); }
  const { data: latest } = await supabase.from("generated_content_versions").select("version").eq("job_id", job.id).eq("entity_type", version.entity_type).eq("entity_key", version.entity_key).order("version", { ascending: false }).limit(1).single(); const nextVersion = (latest?.version ?? version.version) + 1;
  if (parsed.data.action === "save") { const { error } = await supabase.from("generated_content_versions").insert({ job_id: job.id, tenant_id: version.tenant_id, entity_type: version.entity_type, entity_key: version.entity_key, version: nextVersion, provider: "human", model: "platform_admin", prompt_version: "manual-edit-v1", source_fact_ids: version.source_fact_ids, draft_data: parsed.data.draftData, factual_warnings: [], status: "pending", created_by: access.userId }); if (error) return NextResponse.json({ message: error.message }, { status: 409 }); return NextResponse.json({ message: `Manual edit saved as version ${nextVersion}.` }); }
  const provider = getAiProvider(); if (!provider) return NextResponse.json({ message: "Configure OpenAI before regenerating content." }, { status: 503 }); const { data: answerRows } = await supabase.from("onboarding_answers").select("section_key,answer_data").eq("submission_id", job.submission_id); const answers = Object.fromEntries((answerRows ?? []).map((row) => [row.section_key, row.answer_data as Record<string, unknown>])); const result = await provider.generateWebsiteDraft({ entityType: version.entity_type === "page" ? "page" : "project", entityKey: version.entity_key, sourceFacts: buildSourceFacts(answers), tone: typeof answers.content_preferences?.writing_tone === "string" ? answers.content_preferences.writing_tone : "clear and professional", requestedSections: ["introduction", "service context", "call to action"] }); const { error } = await supabase.from("generated_content_versions").insert({ job_id: job.id, tenant_id: version.tenant_id, entity_type: version.entity_type, entity_key: version.entity_key, version: nextVersion, provider: result.provider, model: result.model, prompt_version: "onboarding-page-v1", source_fact_ids: result.sourceFactIds, draft_data: result.draft, factual_warnings: result.factualWarnings, status: "pending", created_by: access.userId }); if (error) return NextResponse.json({ message: error.message }, { status: 409 }); return NextResponse.json({ message: `Regenerated version ${nextVersion}. Human approval is still required.` });
}

