import Image from "next/image";
import Link from "next/link";
import { CheckCircle2, Mail, MapPin, Phone } from "lucide-react";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { CallToAction } from "@/components/call-to-action";
import { ContactForm } from "@/components/contact-form";
import { JsonLd } from "@/components/json-ld";
import { SplitText } from "@/components/motion/split-text";
import { ProjectCard } from "@/components/project-card";
import { pageSchema } from "@/lib/seo/structured-data";
import type { ContentPage, Location, Service, Tenant } from "@/lib/types";

function PageHero({ tenant, page }: { tenant: Tenant; page: ContentPage }) {
  const heroImage = page.heroImage ?? tenant.heroImage;
  return <header className="page-hero"><Image src={heroImage.src} alt={heroImage.alt} fill loading="eager" fetchPriority="high" sizes="100vw" /><div className="container page-hero__content"><Breadcrumbs current={page.breadcrumbLabel} /><p className="eyebrow">{page.intent}</p><SplitText text={page.seo.h1} tag="h1" delay={tenant.theme === "summit" ? 0.045 : 0.07} /><p className="lede">{page.intro}</p></div></header>;
}

function Faq({ items }: { items: Array<{ question: string; answer: string }> }) {
  return <div className="faq">{items.map((item) => <details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</div>;
}

function AboutPage({ tenant, page }: { tenant: Tenant; page: ContentPage }) {
  return <><PageHero tenant={tenant} page={page} /><section className="section"><div className="container grid-2"><div className="prose">{page.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><aside><p className="eyebrow">Service area</p><h2>{tenant.serviceArea}</h2><ul className="link-list"><li><CheckCircle2 size={18} aria-hidden="true" /> Site review and written scope</li><li><CheckCircle2 size={18} aria-hidden="true" /> Protection and preparation plan</li><li><CheckCircle2 size={18} aria-hidden="true" /> Color and sheen confirmation</li><li><CheckCircle2 size={18} aria-hidden="true" /> Final quality walkthrough</li></ul></aside></div></section><section className="section band"><div className="container"><p className="eyebrow">Where we work</p><h2>Local guides for the communities we serve</h2><div className="grid-4">{tenant.locations.slice(0, 8).map((location) => <Link className="card card-link card__body" href={`/${location.slug}`} key={location.id}><h3>{location.city}</h3><p>{location.localDetail}</p></Link>)}</div></div></section><CallToAction tenant={tenant} heading="Bring your surfaces and priorities into focus" /></>;
}

function ContactPage({ tenant, page }: { tenant: Tenant; page: ContentPage }) {
  return <><PageHero tenant={tenant} page={page} /><section className="section"><div className="container grid-2"><div><h2>Contact details</h2><p><Phone size={20} aria-hidden="true" /> <a href={`tel:${tenant.phone.replace(/\D/g, "")}`}>{tenant.phone}</a></p><p><Mail size={20} aria-hidden="true" /> <a href={`mailto:${tenant.email}`}>{tenant.email}</a></p><p><MapPin size={20} aria-hidden="true" /> {tenant.address}</p><p><strong>Hours</strong><br />{tenant.businessHours}</p><p><strong>Service area</strong><br />{tenant.serviceArea}</p><div className="prose">{page.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div><ContactForm serviceArea={tenant.serviceArea} /></div></section><section className="section band"><div className="container"><p className="eyebrow">Popular starting points</p><h2>Check the scope before you send</h2><div className="grid-3">{tenant.services.slice(0, 3).map((service) => <Link className="card card-link card__body" href={`/${service.slug}`} key={service.id}><h3>{service.name}</h3><p>{service.useCases.join(", ")}.</p></Link>)}</div></div></section></>;
}

function GalleryPage({ tenant, page, filter }: { tenant: Tenant; page: ContentPage; filter?: string }) {
  const activeFilter = filter === "interior" || filter === "exterior" ? filter : "all";
  const projects = activeFilter === "all" ? tenant.projects : tenant.projects.filter((project) => project.category === activeFilter);
  return <><PageHero tenant={tenant} page={page} /><section className="section"><div className="container"><nav className="button-row" aria-label="Gallery filters"><Link className={`button ${activeFilter === "all" ? "" : "button--ghost"}`} href="/gallery">All projects</Link><Link className={`button ${activeFilter === "interior" ? "" : "button--ghost"}`} href="/gallery?filter=interior" rel="nofollow">Interior</Link><Link className={`button ${activeFilter === "exterior" ? "" : "button--ghost"}`} href="/gallery?filter=exterior" rel="nofollow">Exterior</Link></nav><div className="grid-3">{projects.map((project) => <ProjectCard key={project.id} project={project} />)}</div></div></section><section className="section band"><div className="narrow"><h2>What a useful project record includes</h2><div className="prose">{page.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><p><Link href="/residential-painting">Review residential services</Link> or <Link href="/commercial-painting">plan a commercial scope</Link>.</p></div></section><CallToAction tenant={tenant} heading="Create the next well-documented project" /></>;
}

function OverviewPage({ tenant, page }: { tenant: Tenant; page: ContentPage }) {
  const residential = page.slug === "residential-painting";
  const services = residential ? tenant.services : tenant.services.filter((service) => ["interior-painting", "exterior-painting", "epoxy-flooring", "brick-painting-staining"].includes(service.slug));
  return <><PageHero tenant={tenant} page={page} /><section className="section"><div className="container grid-2"><div className="prose">{page.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><aside><h2>{residential ? "A home-aware process" : "A site-aware process"}</h2><ol><li>Walk the surfaces and operating constraints.</li><li>Document protection, repairs, products, colors, and sequence.</li><li>Confirm access and application conditions.</li><li>Inspect the finish and complete the handoff.</li></ol></aside></div></section><section className="section band"><div className="container"><p className="eyebrow">Related services</p><h2>{residential ? "Complete residential capabilities" : "Flexible commercial capabilities"}</h2><div className="grid-3">{services.map((service) => <Link className="card card-link card__body" href={`/${service.slug}`} key={service.id}><span className="pill">{service.category}</span><h3>{service.name}</h3><p>{service.intro}</p><strong>Read service details</strong></Link>)}</div></div></section><section className="section"><div className="container grid-2"><div><p className="eyebrow">Relevant projects</p><h2>Work shown with context</h2><div className="grid-2">{tenant.projects.filter((project) => residential || project.name.includes("Commercial") || project.name.includes("Shop")).slice(0, 2).map((project) => <ProjectCard key={project.id} project={project} />)}</div></div><div><p className="eyebrow">Common questions</p><h2>Plan before the first coat</h2><Faq items={[{ question: "How is the work sequence decided?", answer: "The sequence follows access, protection, repairs, product drying, weather, and the areas that must remain usable." }, { question: "Can the scope be phased?", answer: "Yes. A written phase plan should preserve logical stopping points and avoid compromising preparation or coating compatibility." }, { question: "How are products selected?", answer: "Substrate, previous coating, exposure, cleanability, sheen, application conditions, and manufacturer requirements guide product selection." }]} /></div></div></section><CallToAction tenant={tenant} /></>;
}

function ServicePage({ tenant, service }: { tenant: Tenant; service: Service }) {
  const projects = tenant.projects.filter((project) => project.serviceSlugs.includes(service.slug));
  const related = service.relatedSlugs.map((slug) => tenant.services.find((item) => item.slug === slug)).filter((item): item is Service => Boolean(item));
  return <><PageHero tenant={tenant} page={service} /><section className="section"><div className="container grid-2"><div className="prose">{service.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<h2>Where this service fits</h2><ul>{service.useCases.map((item) => <li key={item}>{item}</li>)}</ul><h2>What the plan improves</h2><ul>{service.benefits.map((item) => <li key={item}>{item}</li>)}</ul></div><aside className="card card__body"><p className="eyebrow">Materials considered</p><h2>System components</h2><ul>{service.materials.map((item) => <li key={item}>{item}</li>)}</ul><p className="muted">Final products depend on verified compatibility and site conditions.</p></aside></div></section><section className="section band"><div className="container grid-2"><div><p className="eyebrow">Preparation</p><h2>Make the surface ready</h2><ol>{service.preparation.map((item) => <li key={item}>{item}</li>)}</ol></div><div><p className="eyebrow">Application</p><h2>Build and inspect the finish</h2><ol>{service.process.map((item) => <li key={item}>{item}</li>)}</ol></div></div></section><section className="section"><div className="container grid-2"><div><p className="eyebrow">Customer concerns</p><h2>Questions worth resolving early</h2><ul>{service.concerns.map((item) => <li key={item}>{item}</li>)}</ul><Faq items={service.faq} /></div><div><p className="eyebrow">Relevant project records</p><h2>See the documented scope</h2>{projects.length ? projects.slice(0, 2).map((project) => <ProjectCard key={project.id} project={project} />) : <p>Project evidence is not yet linked. This is a visible SEO warning, not a fabricated claim.</p>}</div></div></section><section className="section band"><div className="container grid-2"><div><h2>Related services</h2><ul className="link-list">{related.map((item) => <li key={item.id}><Link href={`/${item.slug}`}>{item.name}</Link></li>)}</ul></div><div><h2>Service areas</h2><ul className="link-list">{tenant.locations.slice(0, 6).map((location) => <li key={location.id}><Link href={`/${location.slug}`}>{service.name} planning in {location.city}</Link></li>)}</ul></div></div></section><CallToAction tenant={tenant} heading={service.cta} /></>;
}

function LocationPage({ tenant, location }: { tenant: Tenant; location: Location }) {
  const services = location.availableServiceSlugs.map((slug) => tenant.services.find((service) => service.slug === slug)).filter((item): item is Service => Boolean(item));
  const nearby = location.nearby.map((slug) => tenant.locations.find((item) => item.slug === slug)).filter((item): item is Location => Boolean(item));
  const projects = tenant.projects.filter((project) => project.locationSlug === location.slug);
  return <><PageHero tenant={tenant} page={location} /><section className="section"><div className="container grid-2"><div className="prose">{location.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<h2>What is distinctive about {location.city}</h2><p>{location.localDetail}</p><p>Every service remains subject to an on-site scope and actual availability. This guide does not claim unverified neighborhood projects or testimonials.</p></div><aside className="card card__body"><p className="eyebrow">Local contact</p><h2>{tenant.name}</h2><p><a href={`tel:${tenant.phone.replace(/\D/g, "")}`}>{tenant.phone}</a><br /><a href={`mailto:${tenant.email}`}>{tenant.email}</a></p><p>{tenant.businessHours}</p><Link className="button" href="/contact">Request an estimate in {location.city}</Link></aside></div></section><section className="section band"><div className="container"><p className="eyebrow">Available services</p><h2>Painting options for {location.city} properties</h2><div className="grid-4">{services.map((service) => <Link className="card card-link card__body" href={`/${service.slug}`} key={service.id}><h3>{service.name}</h3><p>{service.useCases[0]}</p></Link>)}</div></div></section><section className="section"><div className="container grid-2"><div><p className="eyebrow">Project evidence</p><h2>Work linked to {location.city}</h2>{projects.length ? projects.map((project) => <ProjectCard key={project.id} project={project} />) : <p>No verified local project is linked yet. The dashboard reports this as a content-quality warning.</p>}</div><div><p className="eyebrow">Local questions</p><h2>Planning details</h2><Faq items={location.faq} /><h3>Nearby service areas</h3><ul className="link-list">{nearby.map((item) => <li key={item.id}><Link href={`/${item.slug}`}>Painting services in {item.city}</Link></li>)}</ul></div></div></section><CallToAction tenant={tenant} heading={`Plan a ${location.city} painting scope`} /></>;
}

export function ContentPageView({ tenant, page, galleryFilter }: { tenant: Tenant; page: ContentPage | Service | Location; galleryFilter?: string }) {
  return <><JsonLd data={pageSchema(tenant, page)} />{page.kind === "service" ? <ServicePage tenant={tenant} service={page as Service} /> : page.kind === "location" ? <LocationPage tenant={tenant} location={page as Location} /> : page.slug === "about" ? <AboutPage tenant={tenant} page={page} /> : page.slug === "contact" ? <ContactPage tenant={tenant} page={page} /> : page.slug === "gallery" ? <GalleryPage tenant={tenant} page={page} filter={galleryFilter} /> : <OverviewPage tenant={tenant} page={page} />}</>;
}
