"use client";

import { useState } from "react";
import { LoaderCircle, Save, ShieldAlert } from "lucide-react";

type Domain = { id: string; hostname: string; isPreview: boolean; isPrimary: boolean; isVerified: boolean; ownershipModel?: string; registrar?: string; dnsProvider?: string; vercelStatus: string; sslStatus: string; wwwRedirectVerified: boolean; canonicalVerified: boolean; emailRecordsPreserved: boolean; nameserverChangeAuthorized: boolean; launchStatus: string };

export function DomainTracking({ invitationId, initialDomains, readOnly }: { invitationId: string; initialDomains: Domain[]; readOnly: boolean }) {
  const [domains, setDomains] = useState(initialDomains); const [busy, setBusy] = useState<string | null>(null); const [message, setMessage] = useState("");
  function update(id: string, values: Partial<Domain>) { setDomains((current) => current.map((domain) => domain.id === id ? { ...domain, ...values } : domain)); }
  async function save(domain: Domain) { setBusy(domain.id); const response = await fetch(`/api/platform/onboarding/invitations/${invitationId}/domains/${domain.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(domain) }); const body = await response.json() as { message?: string }; setBusy(null); setMessage(body.message ?? (response.ok ? "Domain status saved." : "Domain status could not be saved.")); }
  return <section className="admin-panel domain-tracking"><h2>Manual domain connection</h2><div className="domain-safety"><ShieldAlert size={20}/><p>Preserve MX, SPF, DKIM, DMARC, and verification records. Do not change nameservers without explicit authorization.</p></div>{domains.map((domain) => <article key={domain.id}><header><div><strong>{domain.hostname}</strong><small>{domain.isPreview ? "Preview domain · permanently noindex" : domain.ownershipModel?.replaceAll("_", " ")}</small></div><span className="status-badge">{domain.launchStatus.replaceAll("_", " ")}</span></header><div className="domain-fields"><label>Vercel status<select value={domain.vercelStatus} disabled={readOnly || domain.isPreview} onChange={(event) => update(domain.id, { vercelStatus: event.target.value })}><option value="not_added">Not added</option><option value="added">Added</option><option value="verified">Verified</option></select></label><label>SSL status<select value={domain.sslStatus} disabled={readOnly || domain.isPreview} onChange={(event) => update(domain.id, { sslStatus: event.target.value })}><option value="pending">Pending</option><option value="issued">Issued</option><option value="failed">Failed</option></select></label><label><input type="checkbox" checked={domain.isVerified} disabled={readOnly || domain.isPreview} onChange={(event) => update(domain.id, { isVerified: event.target.checked })}/> DNS verified</label><label><input type="checkbox" checked={domain.emailRecordsPreserved} disabled={readOnly || domain.isPreview} onChange={(event) => update(domain.id, { emailRecordsPreserved: event.target.checked })}/> Email records preserved</label><label><input type="checkbox" checked={domain.wwwRedirectVerified} disabled={readOnly || domain.isPreview} onChange={(event) => update(domain.id, { wwwRedirectVerified: event.target.checked })}/> www redirect verified</label><label><input type="checkbox" checked={domain.canonicalVerified} disabled={readOnly || domain.isPreview} onChange={(event) => update(domain.id, { canonicalVerified: event.target.checked })}/> Canonical verified</label><label><input type="checkbox" checked={domain.isPrimary} disabled={readOnly || domain.isPreview} onChange={(event) => update(domain.id, { isPrimary: event.target.checked })}/> Primary production domain</label></div>{!domain.isPreview && <button className="button button--ghost" type="button" disabled={readOnly || busy !== null} onClick={() => void save(domain)}>{busy === domain.id ? <LoaderCircle className="spin" size={16}/> : <Save size={16}/>} Save manual checks</button>}</article>)}<p role="status">{message}</p></section>;
}

