"use client";

import { useState } from "react";
import { LoaderCircle, Save } from "lucide-react";

type MediaItem = { id: string; originalFilename: string; sectionKey: string; fieldKey: string; suggestedAltText?: string; approvedAltText?: string; altDecision: string; permissionToPublish: boolean; metadataStripped: boolean; processedOutputs: unknown[] };
function MediaRow({ invitationId, item, readOnly }: { invitationId: string; item: MediaItem; readOnly: boolean }) { const [decision, setDecision] = useState(item.altDecision); const [altText, setAltText] = useState(item.approvedAltText ?? item.suggestedAltText ?? ""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); async function save() { setBusy(true); const response = await fetch(`/api/platform/onboarding/invitations/${invitationId}/media/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision, altText }) }); const body = await response.json() as { message?: string }; setBusy(false); setMessage(body.message ?? (response.ok ? "Image decision saved." : "Image could not be saved.")); } return <article><div><strong>{item.originalFilename}</strong><small>{item.fieldKey.replaceAll(".", " · ")} · {item.processedOutputs.length} responsive file(s) · {item.metadataStripped ? "metadata stripped" : "processing pending"}</small><small>{item.permissionToPublish ? "Publication permission recorded" : "Publication permission missing"}</small></div><label>Alt decision<select value={decision} disabled={readOnly || !item.metadataStripped || !item.permissionToPublish} onChange={(event) => setDecision(event.target.value)}><option value="pending">Pending</option><option value="descriptive">Descriptive</option><option value="decorative">Decorative</option></select></label><label>Approved alt text<input value={altText} disabled={readOnly || decision !== "descriptive"} onChange={(event) => setAltText(event.target.value)}/></label><button className="button button--ghost" type="button" disabled={readOnly || busy || !item.metadataStripped || !item.permissionToPublish} onClick={() => void save()}>{busy ? <LoaderCircle className="spin" size={15}/> : <Save size={15}/>} Save</button>{message && <p role="status">{message}</p>}</article>; }
export function MediaReview({ invitationId, media, readOnly }: { invitationId: string; media: MediaItem[]; readOnly: boolean }) { return <section className="admin-panel media-review"><h2>Processed media and alt text</h2><p>Suggestions remain pending until a human chooses descriptive text or marks a decorative image.</p>{media.map((item) => <MediaRow key={item.id} invitationId={invitationId} item={item} readOnly={readOnly}/>)}</section>; }

