import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { onboardingWriteRequestIsAllowed } from "@/lib/onboarding/request-security";
import { requirePlatformAdmin } from "@/lib/security/dashboard-auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

const schema = z.object({ decision: z.enum(["descriptive", "decorative"]), altText: z.string().trim().max(500) });
export async function PATCH(request: NextRequest, { params }: { params: Promise<{ id: string; mediaId: string }> }) { const access = await requirePlatformAdmin(); if (access.readOnly) return NextResponse.json({ message: "Media review is disabled in demo mode." }, { status: 503 }); const security = onboardingWriteRequestIsAllowed(request, 32_000); if (!security.allowed) return NextResponse.json({ message: security.message }, { status: security.status }); const parsed = schema.safeParse(await request.json()); if (!parsed.success || (parsed.data.decision === "descriptive" && parsed.data.altText.length < 3)) return NextResponse.json({ message: "Approve useful alt text or choose decorative." }, { status: 422 }); const { id, mediaId } = await params; const supabase = createSupabaseAdminClient()!; const { data: media } = await supabase.from("onboarding_files").select("id,processed_outputs,permission_to_publish,metadata_stripped").eq("id", mediaId).eq("invitation_id", id).single(); if (!media || !media.permission_to_publish || !media.metadata_stripped) return NextResponse.json({ message: "This image is not ready for approval." }, { status: 409 }); const approvedAlt = parsed.data.decision === "descriptive" ? parsed.data.altText : null; await supabase.from("onboarding_files").update({ alt_decision: parsed.data.decision, approved_alt_text: approvedAlt, updated_by: access.userId }).eq("id", mediaId); const paths = (Array.isArray(media.processed_outputs) ? media.processed_outputs : []).map((output) => typeof output === "object" && output ? (output as { storagePath?: string }).storagePath : undefined).filter((path): path is string => Boolean(path)); if (paths.length) await supabase.from("project_images").update({ alt_decision: parsed.data.decision, alt_text: approvedAlt, updated_by: access.userId }).in("storage_path", paths); await supabase.from("audit_logs").insert({ actor_id: access.userId, action: "media.alt_decision_approved", entity_type: "onboarding_invitation", entity_id: id, after_data: { media_id: mediaId, decision: parsed.data.decision } }); return NextResponse.json({ message: "Image decision approved." }); }

